### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by grodax** [empiricist/redcontrols#1]
I installed the mod to the server and the console is now constantly emerging errors and server lag.

**Comment by empiricist** [comment]
Uh oh.  Maybe I forgot an @Optional somewhere.  Would it be possible to post an excerpt from the server log?

**Comment by grodax** [comment]
http://pastebin.com/S5SUV4Mf

**Comment by grodax** [comment]
This entire log

**Comment by empiricist** [comment]
That's weird.  I'm not doing anything with entities that should cause them to get flagged as a lag source, and I can't seem to replicate the problem with just Red Controls.  I noticed, though, that it says the world was previously used with some other mods that aren't installed anymore.  Does the same thing happen in a fresh world?  I guess it could be that the entity thing is a false alarm and the lag is something related to that?

**Comment by grodax** [comment]
This happens in pure world. I will try to set a different core.

**Comment by grodax** [comment]
I changed the core server in the recommended version of Forge. Nothing changed. Errors appear in the console as it was.

**Comment by empiricist** [comment]
I just tested with forge 1.7.10-10.13.4.1558-1.7.10 (on both server and client) and I still can't seem to replicate the problem.  Do you know if the problem still occurs without UltraminePlugin?  That looks like it might be the main difference between our setups.

**Comment by grodax** [comment]
I used the same version of Forge. The problem remains.

**Comment by grodax** [comment]
You have enabled advanced opengl?

**Comment by empiricist** [comment]
I also updated java to 1.8.0_66 64bit, and still can't replicate the lag and log messages.  This is getting frustrating.  If I could get the problem to occur on my end, at least I could try profiling it or something to find out where the lag is coming from.

**Comment by grodax** [comment]
it was necessary to allocate more RAM
